---
#My Config
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap
  labels: 
    app_name: myTest-Config
data:
  APP_ENV: DEV
  APP_URL: https://somewhere.com
  APP_DB_NAME: MASTER
  APP_DB_IP: 127.0.0.0
  APP_ROOT: /var


---
#My Secrets
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  labels: 
    app_name: myTest-Config
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret